configMapGenerator:
- files:
  - application.yml
  name: 82238157-configmap
resources:
- ../../base
- pvc.yaml
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
images:
- name: cepgstapacr.azurecr.io/82238157
  newTag: "202410051325"
- name: cepgstapacr.azurecr.io/cloud-sample
  newTag: "202410040944"
